[package]
name = "myrepl"
version = "0.1.0"
authors = ["Reza Handzalah <reza.handzalah@mbiz.co.id>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "9.1.0"
